### PR TITLE
Add target_group_arns to node pool parameters

### PR DESCRIPTION
**Pull request by nikever**
This PR complements the following PR on furyctl repository https://github.com/sighupio/furyctl/pull/50 to address https://github.com/sighupio/furyctl/issues/47.

Please mainly refer to https://github.com/sighupio/furyctl/pull/50 to discuss changes.

### CODE REVIEW

**Comment by angelbarrera92** [comment]
Overall LGTM.

What I can say is to use the `eks_` prefix in this field as it does not belongs to the "soft-interface" and I don't think other cloud providers have this concept. 

Consider also update the terraform module docs using `terraform-docs`.

**Review by angelbarrera92 — APPROVED** [review]
LGTM!

**Review by lnovara — APPROVED** [review]
LGMT! :shipit: 

Minor nit: consider running the Terraform code through `terraform fmt`.

**Comment by nikever** [comment]
> LGMT! :shipit:
> 
> Minor nit: consider running the Terraform code through `terraform fmt`.

Already ran `terraform fmt` <3 

I'm merging and releasing a new version.

**Pull request merged**
